name: Generate Podcast feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator@v3
        uses: PumuduRajakaruna/podcast-generator@main
        with: 
            email: ${{ github.actor }}@users.noreply.github.com
            name: ${{ github.actor }}
        
           
